/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/depreciation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Depreciation */
        get: operations["depreciation_depreciation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/comps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Comps */
        get: operations["market_comps_market_comps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obd/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obd Snapshot */
        get: operations["obd_snapshot_obd_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/obd/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obd Stream
         * @description SSE stream of ObdSnapshotOut payloads (implemented in Phase 03).
         */
        get: operations["obd_stream_obd_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odx/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Odx Faults */
        get: operations["odx_faults_odx_faults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicle/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_vehicle_profile_get"];
        /** Put Profile */
        put: operations["put_profile_vehicle_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["create_booking_booking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookingIn */
        BookingIn: {
            /** Profile Id */
            profile_id: number;
            /** Name */
            name: string;
            /** Workshop */
            workshop: string;
            /** Car Model */
            car_model: string;
            /** Purpose */
            purpose: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
        };
        /** BookingOut */
        BookingOut: {
            /** Booking Id */
            booking_id: number;
            /** Status */
            status: string;
            /** Dispatched */
            dispatched: boolean;
            /** Dry Run */
            dry_run: boolean;
        };
        /** DepreciationOut */
        DepreciationOut: {
            /** Points */
            points: components["schemas"]["DepreciationPoint"][];
        };
        /** DepreciationPoint */
        DepreciationPoint: {
            /** Year */
            year: number;
            /** Value Rm */
            value_rm: number;
            /** Retained Pct */
            retained_pct: number;
        };
        /** FaultOut */
        FaultOut: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Severity */
            severity: string;
            /** System */
            system: string;
        };
        /** FaultsOut */
        FaultsOut: {
            /** Faults */
            faults: components["schemas"]["FaultOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MarketCompsOut */
        MarketCompsOut: {
            /** Comps */
            comps: components["schemas"]["MarketListingOut"][];
            /** Median Rm */
            median_rm: number | null;
            /** Delta Pct */
            delta_pct: number | null;
            /** N */
            n: number;
        };
        /** MarketListingOut */
        MarketListingOut: {
            /**
             * Source
             * @enum {string}
             */
            source: "mudah" | "carlist";
            /** Listing Url */
            listing_url: string;
            /** Model */
            model: string;
            /** Variant */
            variant?: string | null;
            /** Year */
            year: number;
            /** Price Rm */
            price_rm: number;
            /** Mileage */
            mileage?: number | null;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
        };
        /** ObdSnapshotOut */
        ObdSnapshotOut: {
            /** Rpm */
            rpm: number;
            /** Coolant C */
            coolant_c: number;
            /** Battery V */
            battery_v: number;
            /** Health */
            health: number;
            /** Odo Km */
            odo_km: number;
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** PredictOut */
        PredictOut: {
            /** Value Rm */
            value_rm: number;
            /** Low Rm */
            low_rm: number;
            /** High Rm */
            high_rm: number;
            /** Confidence */
            confidence: number;
            /**
             * Currency
             * @default RM
             * @constant
             */
            currency: "RM";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleProfileIn */
        VehicleProfileIn: {
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Mileage */
            mileage: number;
            /** Transmission */
            transmission: string;
            /** Fuel Type */
            fuel_type: string;
            /** Engine Size */
            engine_size: number;
            /** Mpg */
            mpg?: number | null;
            /** Tax */
            tax?: number | null;
            /** Service History Count */
            service_history_count?: number | null;
            /** Service History Total */
            service_history_total?: number | null;
        };
        /** VehicleProfileOut */
        VehicleProfileOut: {
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Mileage */
            mileage: number;
            /** Transmission */
            transmission: string;
            /** Fuel Type */
            fuel_type: string;
            /** Engine Size */
            engine_size: number;
            /** Mpg */
            mpg?: number | null;
            /** Tax */
            tax?: number | null;
            /** Service History Count */
            service_history_count?: number | null;
            /** Service History Total */
            service_history_total?: number | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Workshop */
            workshop?: string | null;
            /** Glb Asset */
            glb_asset?: string | null;
            /** Service History Max */
            service_history_max?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    predict_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    depreciation_depreciation_get: {
        parameters: {
            query: {
                profile_id: number;
                years?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepreciationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_comps_market_comps_get: {
        parameters: {
            query: {
                model: string;
                year?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketCompsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obd_snapshot_obd_snapshot_get: {
        parameters: {
            query: {
                profile_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObdSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obd_stream_obd_stream_get: {
        parameters: {
            query: {
                profile_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    odx_faults_odx_faults_get: {
        parameters: {
            query: {
                profile_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_vehicle_profile_get: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_vehicle_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_booking_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
